### ISSUE TITLE
Input_requirement

### ISSUE THREAD

**Issue by justintiger** [aimagelab/RefiNet#2]
Hi Thank for this nice model.
I have a question about the input parameters. Should i also have a file with keypoints of input? Or can i only have depth maps as input and return me 3D-skeleton?

**Comment by Deusy94** [comment]
Hi @justintiger, thank you for reaching out.
Our method need a starting set of keypoints which are then refined with the 3 steps.
You can use any of the already developed method to get a starting pose to work with, like:
[Hrnet](https://github.com/stefanopini/simple-HRNet), [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose), or even using Shotton algorithm from kinect.
